[tool.poetry]
name = "scikit-explain"
version = "0.1.0"
description = "This package is a toolkit of eXplainable Artificial Integillence (XAI) methods to interpret sklearn models."
authors = ["Arthur Selle Jacobs <asjacobs@inf.ufrgs.br>"]
packages = [ { include = "skexplain"} ]


[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.19.1"
scipy = "^1.5.2"
pandas = "^1.1.0"
pydotplus = "^2.0.2"
scikit-learn = "^0.23.2"
matplotlib = "^3.3.1"
imbalanced-learn = "^0.7.0"
rootpath = "^0.1.1"
setuptools = "^49.6.0"
dtextract = {path = "../dtextract"}
scikit-multiflow = "^0.5.3"
shap = "^0.36.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
